kafka-consumer-service {
  kafka-bootstrap = ${?KAFKA_BROKERS}
  #kafka-bootstrap = "localhost:9092,localhost:9093,localhost:9094"
  group-id = "notification-consumer-group"
  topic = "notifications"
}

akka {
  loglevel = "INFO"
}

mail {
  host = "smtp.gmail.com"
  port = 587
  user = "sownthariponnusamy@gmail.com"
  password = "ibks gmgm sooi hkhi"
  tls = true
}
